### ISSUE TITLE
"No Info" on is_yomtov

### ISSUE THREAD

**Issue by aviadlevy** [rt400/Jewish-Sabbaths-Holidays#11]
Hi,
First of all, thanks for this integration

I think the current response for is_yomtov ("No Info") is not good. I would hope to get False.

1. Can you explain the current behavior and whether this is intentional?
2. Do you think we can change it so No Info - would be False instead?

If your answer to 2 is yes, I would love to try and open a PR for this change and contribute my first contribution for the HASS community

Thanks

**Comment by aviadlevy** [comment]
P. S. I know this "issue" can be solved by conditioning:

```yaml
condition: not 
conditions: 
  - condition: state 
    entity_id: sensor.hebcal_is_yomtov 
    state: 'True'
```

But still I can't understand the meaning of No Info and why it's not just False
